package practica5;
// Generated 11-dic-2020 1:00:30 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private Integer codDept;
	private String nombre;
	private String direccion;
	private Integer objetivos;
	private Set<Empleados> empleadoses = new HashSet<Empleados>(0);

	public Departamentos() {
	}

	public Departamentos(String nombre, String direccion, Integer objetivos, Set<Empleados> empleadoses) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.objetivos = objetivos;
		this.empleadoses = empleadoses;
	}

	public Integer getCodDept() {
		return this.codDept;
	}

	public void setCodDept(Integer codDept) {
		this.codDept = codDept;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Integer getObjetivos() {
		return this.objetivos;
	}

	public void setObjetivos(Integer objetivos) {
		this.objetivos = objetivos;
	}

	public Set<Empleados> getEmpleadoses() {
		return this.empleadoses;
	}

	public void setEmpleadoses(Set<Empleados> empleadoses) {
		this.empleadoses = empleadoses;
	}

}
